music_directory		"~/Música"
playlist_directory	"~/Música/Playlist"
# added from another config file
db_file "~/.config/mpd/mpd.db"
pid_file "~/.config/mpd/pid"
state_file "~/.config/mpd/state"
# log_file "syslog"

auto_update "yes"
bind_to_address "127.0.0.1" # not the same as localhost
restore_paused "yes"
port "6600"
max_output_buffer_size "16384"

audio_output {
        type            "pipewire"
        name            "PipeWire Sound Server"
}

audio_output {
       type	"fifo"
       name	"Visualizer feed"
       path	"/tmp/mpd.fifo"
       format	"44100:16:2"
}
