l no-osd seek 3 exact
h no-osd seek -3 exact
RIGHT no-osd seek 5 exact
LEFT  no-osd seek -5 exact
Ctrl+LEFT   no-osd sub-seek -1         # seek to the previous subtitle
Ctrl+RIGHT  no-osd sub-seek  1         # seek to the next subtitle
j seek -60
k seek 60
R ab-loop
I seek 0 absolute
a cycle audio
c cycle sub
s screenshot
S screenshot video
