screenshot-directory=~/Escritorio/mpv
save-position-on-quit
sub-auto=fuzzy
profile=high-quality

[extension.gif]
osc=no
loop-file

[high-quality]
# Describe this profile
profile-desc="High quality rendering"

# Disable debanding for better performance
deband=no
deband-iterations=4 # deband steps
deband-threshold=35 # deband strength
deband-range=16 # deband range
deband-grain=5 # dynamic grain: set to "0" if using the static grain shader

# display-fps-override=60
video-sync=display-resample
interpolation=yes
tscale=oversample # smoothmotion

vo=gpu-next
fullscreen=no
target-colorspace-hint=no
target-contrast=auto
gpu-api=vulkan
hwdec=auto # enable best HW decoder; turn off for software decoding ctrl h to toggle it
gpu-hwdec-interop=vaapi # fix missing libcuda

reset-on-next-file=audio-delay,mute,pause,speed,sub-delay,video-aspect-override,video-pan-x,video-pan-y,video-rotate,video-zoom,volume

log-file=~~/log           #Sets a location for writing a log file, ~~/ translates to ~/.config/mpv

# Enable IPC support to control mpv from the command line
input-ipc-server=/tmp/mpv.sock

# audio language priority
alang=ja,jp,jpn,es,en,eng
