# temas
include GruvBox_DarkHard.conf
#include Wryan.conf
#include VSCode_Dark.conf

allow_remote_control yes
enabled_layouts tall

# opacidad y efecto borroso del fondo
dynamic_background_opacity yes
background_opacity 0.80
background_blur 1

# avanzado
term xterm-kitty

# sonido de la campana
enable_audio_bell yes

# ajustes específicos del SO (decoración de ventana Gnome para Wayland)
# linux_display_server x11
# linux_display_server wayland

# fuente
font_family        Fira Code Nerd Font Propo
font_size 12

# administración del tamaño de la fuente
map ctrl+shift+backspace change_font_size all 0

# increase font size
map ctrl+shift+k change_font_size all +1

# decrease font size
map ctrl+shift+j change_font_size all -1

# personalización del cursor
# bloque / rayo / subrayado
cursor_shape block
cursor_blink_interval 1
cursor_stop_blinking_after 0

shell zsh
shell_integration no-cursor

# historial de desplazamiento
scrollback_lines 5000
wheel_scroll_multiplier 3.0

# ratón
mouse_hide_wait -1

# diseño de la ventana
remember_window_size  yes
initial_window_width  1200
initial_window_height 750
window_border_width 1.5pt
enabled_layouts tall
window_padding_width 0
window_margin_width 2
hide_window_decorations no

# administración de ventanas
map ctrl+shift+enter new_window
map ctrl+shift+] next_window
map ctrl+shift+[ previous_window

# administración de diseños
map ctrl+alt+l next_layout
map ctrl+alt+r goto_layout tall
map ctrl+alt+s goto_layout stack

# personalización de la barra de pestañas
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_edge bottom
tab_bar_align left
active_tab_font_style   bold
inactive_tab_font_style normal

# administración de pestañas
map ctrl+shift+a new_tab
map ctrl+shift+l next_tab
map ctrl+shift+h previous_tab
map ctrl+shift+q close_tab

# clipboard
clipboard_control write-clipboard read-clipboard
copy_on_select    yes
map alt+c         copy_to_clipboard
map alt+v         paste_from_clipboard
# map shift+insert paste_from_clipboard

# Increase, decrease or return opacity to default from kitty itself (not picom)
map ctrl+shift+plus set_background_opacity +0.1
map ctrl+shift+minus set_background_opacity -0.1
map ctrl+shift+d set_background_opacity default

map ctrl+k scroll_line_up
map ctrl+j scroll_line_down
